In [1]:
print("OK")

OK

In [80]:
import numpy as np
import pandas as pd

In [81]:
df =pd.read_csv("customer.csv")
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [82]:
df.sample(5)

    age  gender   review education purchased
7    60  Female     Poor    School       Yes
31   22  Female     Poor    School       Yes
10   98  Female     Good        UG       Yes
39   76    Male     Poor        PG        No
34   86    Male  Average    School        No

In [83]:
df=df.iloc[:,2: ]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

## Ordinal Encoding

In [84]:
from sklearn.preprocessing import OrdinalEncoder

In [85]:
x=df.drop('purchased',axis=1)
y=df['purchased']

In [86]:
x.head()

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

In [87]:
y.head()

0    No
1    No
2    No
3    No
4    No
Name: purchased, dtype: object

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)

In [89]:
df.shape

(50, 3)

In [90]:
x_train.shape, x_test.shape

((35, 2), (15, 2))

In [91]:
df.shape

(50, 3)

In [92]:
x_train

     review education
6      Good    School
41     Good        PG
46     Poor        PG
47     Good        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
24  Average        PG
34  Average    School
31     Poor    School
0   Average    School
44  Average        UG
27     Poor        PG
33     Good        PG
5   Average    School
29  Average        UG
11     Good        UG
36     Good        UG
1      Poor        UG
21  Average        PG
2      Good        PG
43     Poor        PG
35     Poor    School
23     Good    School
40     Good    School
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

In [93]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [94]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [95]:
x_train_tra=oe.transform(x_train)

In [96]:
x_train_tra

array([[2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

## label Encoding

In [100]:
from sklearn.preprocessing import LabelEncoder

In [101]:
le=LabelEncoder()

In [102]:
le.fit(y_train)
y_train_tr=le.transform(y_train)
y_test_tr=le.transform(y_test)

In [103]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [104]:
y_train_tr

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [105]:
y_test_tr

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0])

## One hot encoding

In [107]:
df =pd.read_csv("customer.csv")
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [108]:
df['gender'].value_counts()

gender
Female    29
Male      21
Name: count, dtype: int64

In [110]:
df.shape

(50, 5)

In [118]:
from sklearn.preprocessing import OneHotEncoder

In [120]:
onh=OneHotEncoder(sparse_output=False)

In [121]:
new_data=onh.fit_transform(df[['gender']])

In [122]:
new_data

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [123]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [125]:
pd.get_dummies(df,columns=['gender'])

    age   review education purchased  gender_Female  gender_Male
0    30  Average    School        No           True        False
1    68     Poor        UG        No           True        False
2    70     Good        PG        No           True        False
3    72     Good        PG        No           True        False
4    16  Average        UG        No           True        False
5    31  Average    School       Yes           True        False
6    18     Good    School        No          False         True
7    60     Poor    School       Yes           True        False
8    65  Average        UG        No           True        False
9    74     Good        UG       Yes          False         True
10   98     Good        UG       Yes           True        False
11   74     Good        UG       Yes          False         True
12   51     Poor    School        No          False         True
13   57  Average    School        No           True        False
14   15     Poor        PG       Yes          False         True
15   75     Poor        UG        No          False         True
16   59     Poor        UG       Yes          False         True
17   22     Poor        UG       Yes           True        False
18   19     Good    School        No          False         True
19   97     Poor        PG       Yes          False         True
20   57  Average    School       Yes           True        False
21   32  Average        PG        No          False         True
22   18     Poor        PG       Yes           True        False
23   96     Good    School        No           True        False
24   16  Average        PG       Yes           True        False
25   57     Good    School        No           True        False
26   53     Poor        PG        No           True        False
27   69     Poor        PG        No           True        False
28   48     Poor    School        No          False         True
29   83  Average        UG       Yes           True        False
30   73  Average        UG        No          False         True
31   22     Poor    School       Yes           True        False
32   92  Average        UG       Yes          False         True
33   89     Good        PG       Yes           True        False
34   86  Average    School        No          False         True
35   74     Poor    School       Yes          False         True
36   34     Good        UG       Yes           True        False
37   94  Average        PG       Yes          False         True
38   45     Good    School        No           True        False
39   76     Poor        PG        No          False         True
40   39     Good    School        No          False         True
41   23     Good        PG       Yes          False         True
42   30     Good        PG       Yes           True        False
43   27     Poor        PG        No          False         True
44   77  Average        UG        No           True        False
45   61     Poor        PG       Yes          False         True
46   64     Poor        PG        No           True        False
47   38     Good        PG       Yes           True        False
48   39     Good        UG       Yes           True        False
49   25     Good        UG        No           True        False