In [1]:
print("OK")

OK

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df['cough'].unique()

array(['Mild', 'Strong'], dtype=object)

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [15]:
x=df.drop(columns=['has_covid'],axis=1)
y=df['has_covid']

In [16]:
x.head()

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai

In [17]:
y.head()

0     No
1    Yes
2     No
3     No
4     No
Name: has_covid, dtype: object

In [20]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.20, random_state=43)

In [22]:
df.shape, x_train.shape, x_test.shape, y_train.shape, y_test.shape

((100, 6), (80, 5), (20, 5), (80,), (20,))